# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='openable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='refrigerated',
            field=models.BooleanField(default=False),
        ),
    ]
