# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160321_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='opened_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
