# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160322_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='opened',
        ),
    ]
