# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160329_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='freezer_expiration_term',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='open_expiration_term',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
