# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160405_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGroceryDatabaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_id', models.IntegerField()),
                ('product_brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_upc', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='itemtype',
            name='open_grocery_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.OpenGroceryDatabaseEntry'),
        ),
    ]
