# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160407_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('refrigerated', models.BooleanField(default=False)),
                ('frozen', models.BooleanField(default=False)),
            ],
        ),
    ]
