# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_location_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='frozen_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='name_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='refrigerated_changed',
            field=models.BooleanField(default=False),
        ),
    ]
