# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160409_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='frozen_changed',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name_changed',
        ),
        migrations.RemoveField(
            model_name='location',
            name='refrigerated_changed',
        ),
        migrations.AddField(
            model_name='location',
            name='name_default',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
