# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20160410_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='temperature_needs',
            field=models.SmallIntegerField(default=2),
        ),
    ]
