# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_itemtype_temperature_needs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='temperature_needs',
            new_name='needed_temperature',
        ),
    ]
