# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20160410_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='improperly_stored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='location_date',
            field=models.DateField(null=True),
        ),
    ]
