# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20160410_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='open_grocery_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.OpenGroceryDatabaseEntry'),
        ),
    ]
