# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20160410_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='improperly_stored',
            new_name='_improperly_stored',
        ),
    ]
