# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20160410_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtypedefault',
            name='freezer_expiration_term',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='itemtypedefault',
            name='name',
            field=models.CharField(default='[NAME]', max_length=150),
        ),
        migrations.AddField(
            model_name='itemtypedefault',
            name='needed_temperature',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='itemtypedefault',
            name='open_expiration_term',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='itemtypedefault',
            name='openable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
