# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20160410_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='default',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name_default',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemTypeDefault'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
