# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20160410_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='default',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ItemType'),
        ),
        migrations.DeleteModel(
            name='ItemTypeDefault',
        ),
    ]
