# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20160410_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemType'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='open_grocery_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.OpenGroceryDatabaseEntry'),
        ),
    ]
