# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20160501_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='printed_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
