# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='needs_password_reset',
            new_name='_needs_password_reset',
        ),
    ]
