# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20160509_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='initialized',
            field=models.BooleanField(default=True),
        ),
    ]
