# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationmodel_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='id_string',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='post_date',
            field=models.DateField(default=datetime.date(2016, 5, 23)),
            preserve_default=False,
        ),
    ]
